org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.java.installations.auto-download=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
loom_version=1.16.1
kotlin_version=2.3.21
fabric_api_version=0.141.3+1.21.11
fabric_language_kotlin_version=1.13.11+kotlin.2.3.21

mod_version=0.1.0
maven_group=dev.nexaddons
archives_base_name=nexaddons
